version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
    ports:
    - 4369:4369
    - 5671:5671
    - 5672:5672
    - 25672:25672
    - 15671:15671
    - 15672:15672
    
  lb:
    build: ./LB
    ports:
      - 80:80

  psn:
    # scale: 3
    build: ./psn
    restart: always
    volumes:
        - ./.docker/storage:/app/shared
    environment:
        "storage:path": shared

  ml:
    # scale: 2
    build: ./ml
    restart: always

  sn:
    build: ./sn
    restart: always
    volumes:
        - ./.docker/sn:/app/database
    ports:
        - 81:80

  # ui:
    # build: ./UI
    # ports:
    # - 4200:80